update numpy version to 1.20
Due to issue: 
ImportError: numpy.core.multiarray failed to import 
RuntimeError: module compiled against API version 0xe but this version of numpy is 0xd