Revert "Refine positions in real space as well, not just reciprocal space"
This reverts commit 9645aa965c6815fb32be0bbd91c8846be871bc4f.

We can't do real-space refinement, because we reliably encounter this crash cause.
Still can't work out why it pops up.

========================= Local real-space refinement =========================

Before:
  r_work=0.2360 r_free=0.2764
  24 residues out of total 85 (non-ALA, GLY, PRO) need a fit.
    rotamer outliers: 8
    poor density    : 16
  time to evaluate  : 0.154
Traceback (most recent call last):
  File "/opt/phenix-1.18.2-3874/build/../modules/phenix/phenix/command_line/refine.py", line 11, in <module>
    command_line.run(command_name="phenix.refine", args=sys.argv[1:])
  File "/opt/phenix-1.18.2-3874/modules/phenix/phenix/refinement/command_line.py", line 125, in run
    refine_object.run(call_back_handler=call_back_handler)
  File "/opt/phenix-1.18.2-3874/modules/phenix/phenix/refinement/driver.py", line 339, in run
    call_back_handler       = call_back_handler).result
  File "/opt/phenix-1.18.2-3874/modules/phenix/phenix/refinement/strategies.py", line 215, in __init__
    ion_placement_manager = ion_placement_manager)
  File "/opt/phenix-1.18.2-3874/modules/phenix/phenix/refinement/macro_cycle.py", line 86, in __init__
    self.call(self.realsrl,  "Local real-space refinement")
  File "/opt/phenix-1.18.2-3874/modules/phenix/phenix/refinement/macro_cycle.py", line 126, in call
    func(prefix = prefix)
  File "/opt/phenix-1.18.2-3874/modules/phenix/phenix/refinement/macro_cycle.py", line 306, in realsrl
    log           = self.log)
  File "/opt/phenix-1.18.2-3874/modules/phenix/phenix/refinement/xyz_real_space.py", line 158, in run_local
    log               = log)
  File "/opt/phenix-1.18.2-3874/modules/cctbx_project/mmtbx/refinement/real_space/fit_residues.py", line 87, in __init__
    self.loop(function = self.one_residue_iteration)
  File "/opt/phenix-1.18.2-3874/modules/cctbx_project/mmtbx/refinement/real_space/fit_residues.py", line 182, in loop
    function(residue = residue)
  File "/opt/phenix-1.18.2-3874/modules/cctbx_project/mmtbx/refinement/real_space/fit_residues.py", line 155, in one_residue_iteration
    residue=residue, radius=negate_rad)
  File "/opt/phenix-1.18.2-3874/modules/cctbx_project/mmtbx/refinement/real_space/fit_residues.py", line 144, in get_nonbonded_bumpers
    if(mv < self.cmv[key]/3): good = False
KeyError: 'A_TYR_CE1'